# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_User_Data_Dialog.ui'
#
# Created: Fri Oct  2 17:54:26 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialog_User_Data(object):
    def setupUi(self, dialog_User_Data):
        dialog_User_Data.setObjectName(_fromUtf8("dialog_User_Data"))
        dialog_User_Data.resize(640, 680)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog_User_Data.sizePolicy().hasHeightForWidth())
        dialog_User_Data.setSizePolicy(sizePolicy)
        dialog_User_Data.setMinimumSize(QtCore.QSize(640, 680))
        dialog_User_Data.setMaximumSize(QtCore.QSize(640, 680))
        dialog_User_Data.setWindowOpacity(1.0)
        dialog_User_Data.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(98, 98, 98, 255), stop:1 rgba(199, 199, 199, 255));"))
        dialog_User_Data.setSizeGripEnabled(False)
        dialog_User_Data.setModal(False)
        self.horizontalLayout_5 = QtGui.QHBoxLayout(dialog_User_Data)
        self.horizontalLayout_5.setMargin(2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_4 = QtGui.QLabel(dialog_User_Data)
        self.label_4.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setContentsMargins(24, -1, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(dialog_User_Data)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label.setPalette(palette)
        self.label.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit__Dialog_User_data_User_ID = QtGui.QLineEdit(dialog_User_Data)
        self.lineEdit__Dialog_User_data_User_ID.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.lineEdit__Dialog_User_data_User_ID.setText(_fromUtf8(""))
        self.lineEdit__Dialog_User_data_User_ID.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit__Dialog_User_data_User_ID.setObjectName(_fromUtf8("lineEdit__Dialog_User_data_User_ID"))
        self.horizontalLayout.addWidget(self.lineEdit__Dialog_User_data_User_ID)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(1, 10)
        self.horizontalLayout.setStretch(2, 4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(dialog_User_Data)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_2.setPalette(palette)
        self.label_2.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_Dialog_User_data_User_Name = QtGui.QLineEdit(dialog_User_Data)
        self.lineEdit_Dialog_User_data_User_Name.setObjectName(_fromUtf8("lineEdit_Dialog_User_data_User_Name"))
        self.horizontalLayout_2.addWidget(self.lineEdit_Dialog_User_data_User_Name)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton_Dialog_User_Data_Lookup = QtGui.QPushButton(dialog_User_Data)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Dialog_User_Data_Lookup.sizePolicy().hasHeightForWidth())
        self.pushButton_Dialog_User_Data_Lookup.setSizePolicy(sizePolicy)
        self.pushButton_Dialog_User_Data_Lookup.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_Dialog_User_Data_Lookup.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_Dialog_User_Data_Lookup.setStyleSheet(_fromUtf8("\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.pushButton_Dialog_User_Data_Lookup.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/View/img/view_count.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Dialog_User_Data_Lookup.setIcon(icon)
        self.pushButton_Dialog_User_Data_Lookup.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_Dialog_User_Data_Lookup.setAutoDefault(False)
        self.pushButton_Dialog_User_Data_Lookup.setDefault(True)
        self.pushButton_Dialog_User_Data_Lookup.setFlat(False)
        self.pushButton_Dialog_User_Data_Lookup.setObjectName(_fromUtf8("pushButton_Dialog_User_Data_Lookup"))
        self.horizontalLayout_2.addWidget(self.pushButton_Dialog_User_Data_Lookup)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_2.setStretch(1, 10)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(dialog_User_Data)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_3.setPalette(palette)
        self.label_3.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_Dialog_User_data_Password = QtGui.QLineEdit(dialog_User_Data)
        self.lineEdit_Dialog_User_data_Password.setInputMask(_fromUtf8(""))
        self.lineEdit_Dialog_User_data_Password.setObjectName(_fromUtf8("lineEdit_Dialog_User_data_Password"))
        self.horizontalLayout_3.addWidget(self.lineEdit_Dialog_User_data_Password)
        self.checkBox_Widget_User_Data_Show_Password = QtGui.QCheckBox(dialog_User_Data)
        self.checkBox_Widget_User_Data_Show_Password.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.checkBox_Widget_User_Data_Show_Password.setPalette(palette)
        self.checkBox_Widget_User_Data_Show_Password.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);"))
        self.checkBox_Widget_User_Data_Show_Password.setTristate(False)
        self.checkBox_Widget_User_Data_Show_Password.setObjectName(_fromUtf8("checkBox_Widget_User_Data_Show_Password"))
        self.horizontalLayout_3.addWidget(self.checkBox_Widget_User_Data_Show_Password)
        self.horizontalLayout_3.setStretch(1, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 52, -1, -1)
        self.gridLayout.setHorizontalSpacing(12)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 2, 1, 1)
        self.pushButton__Dialog_User_data_Log_In = QtGui.QPushButton(dialog_User_Data)
        self.pushButton__Dialog_User_data_Log_In.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 255);"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Log in/img/00c3ff-login-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__Dialog_User_data_Log_In.setIcon(icon1)
        self.pushButton__Dialog_User_data_Log_In.setCheckable(False)
        self.pushButton__Dialog_User_data_Log_In.setChecked(False)
        self.pushButton__Dialog_User_data_Log_In.setAutoDefault(True)
        self.pushButton__Dialog_User_data_Log_In.setFlat(False)
        self.pushButton__Dialog_User_data_Log_In.setObjectName(_fromUtf8("pushButton__Dialog_User_data_Log_In"))
        self.gridLayout.addWidget(self.pushButton__Dialog_User_data_Log_In, 0, 0, 1, 1)
        self.label_Dialog_User_data_Status_Icon = QtGui.QLabel(dialog_User_Data)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Dialog_User_data_Status_Icon.sizePolicy().hasHeightForWidth())
        self.label_Dialog_User_data_Status_Icon.setSizePolicy(sizePolicy)
        self.label_Dialog_User_data_Status_Icon.setMinimumSize(QtCore.QSize(32, 32))
        self.label_Dialog_User_data_Status_Icon.setMaximumSize(QtCore.QSize(32, 32))
        self.label_Dialog_User_data_Status_Icon.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.label_Dialog_User_data_Status_Icon.setText(_fromUtf8(""))
        self.label_Dialog_User_data_Status_Icon.setPixmap(QtGui.QPixmap(_fromUtf8(":/Offline/img/969696-disconnected-32.png")))
        self.label_Dialog_User_data_Status_Icon.setObjectName(_fromUtf8("label_Dialog_User_data_Status_Icon"))
        self.gridLayout.addWidget(self.label_Dialog_User_data_Status_Icon, 0, 1, 1, 1)
        self.textEdit_Dialog_User_data_Listing = QtGui.QTextEdit(dialog_User_Data)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_Dialog_User_data_Listing.sizePolicy().hasHeightForWidth())
        self.textEdit_Dialog_User_data_Listing.setSizePolicy(sizePolicy)
        self.textEdit_Dialog_User_data_Listing.setMinimumSize(QtCore.QSize(300, 150))
        self.textEdit_Dialog_User_data_Listing.setMaximumSize(QtCore.QSize(300, 150))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textEdit_Dialog_User_data_Listing.setPalette(palette)
        self.textEdit_Dialog_User_data_Listing.setAutoFillBackground(False)
        self.textEdit_Dialog_User_data_Listing.setStyleSheet(_fromUtf8("background-color: rgba(50, 50, 50, 150);\n"
"font: 8pt \"Monospace\";"))
        self.textEdit_Dialog_User_data_Listing.setReadOnly(True)
        self.textEdit_Dialog_User_data_Listing.setObjectName(_fromUtf8("textEdit_Dialog_User_data_Listing"))
        self.gridLayout.addWidget(self.textEdit_Dialog_User_data_Listing, 1, 0, 1, 4)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.listWidget__Dialog_User_data_Users = QtGui.QListWidget(dialog_User_Data)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget__Dialog_User_data_Users.sizePolicy().hasHeightForWidth())
        self.listWidget__Dialog_User_data_Users.setSizePolicy(sizePolicy)
        self.listWidget__Dialog_User_data_Users.setMinimumSize(QtCore.QSize(628, 380))
        self.listWidget__Dialog_User_data_Users.setMaximumSize(QtCore.QSize(628, 380))
        self.listWidget__Dialog_User_data_Users.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255,120);"))
        self.listWidget__Dialog_User_data_Users.setFrameShape(QtGui.QFrame.WinPanel)
        self.listWidget__Dialog_User_data_Users.setFrameShadow(QtGui.QFrame.Sunken)
        self.listWidget__Dialog_User_data_Users.setAutoScroll(False)
        self.listWidget__Dialog_User_data_Users.setAutoScrollMargin(0)
        self.listWidget__Dialog_User_data_Users.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listWidget__Dialog_User_data_Users.setTabKeyNavigation(True)
        self.listWidget__Dialog_User_data_Users.setProperty("showDropIndicator", False)
        self.listWidget__Dialog_User_data_Users.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.listWidget__Dialog_User_data_Users.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.listWidget__Dialog_User_data_Users.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.listWidget__Dialog_User_data_Users.setIconSize(QtCore.QSize(0, 0))
        self.listWidget__Dialog_User_data_Users.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.listWidget__Dialog_User_data_Users.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.listWidget__Dialog_User_data_Users.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.listWidget__Dialog_User_data_Users.setMovement(QtGui.QListView.Static)
        self.listWidget__Dialog_User_data_Users.setFlow(QtGui.QListView.LeftToRight)
        self.listWidget__Dialog_User_data_Users.setProperty("isWrapping", True)
        self.listWidget__Dialog_User_data_Users.setResizeMode(QtGui.QListView.Fixed)
        self.listWidget__Dialog_User_data_Users.setLayoutMode(QtGui.QListView.SinglePass)
        self.listWidget__Dialog_User_data_Users.setSpacing(1)
        self.listWidget__Dialog_User_data_Users.setGridSize(QtCore.QSize(152, 120))
        self.listWidget__Dialog_User_data_Users.setViewMode(QtGui.QListView.IconMode)
        self.listWidget__Dialog_User_data_Users.setModelColumn(0)
        self.listWidget__Dialog_User_data_Users.setUniformItemSizes(False)
        self.listWidget__Dialog_User_data_Users.setBatchSize(100)
        self.listWidget__Dialog_User_data_Users.setWordWrap(True)
        self.listWidget__Dialog_User_data_Users.setSelectionRectVisible(True)
        self.listWidget__Dialog_User_data_Users.setObjectName(_fromUtf8("listWidget__Dialog_User_data_Users"))
        self.verticalLayout_2.addWidget(self.listWidget__Dialog_User_data_Users)
        self.buttonBox_Dialog_User_data_Save_Cancel = QtGui.QDialogButtonBox(dialog_User_Data)
        self.buttonBox_Dialog_User_data_Save_Cancel.setAutoFillBackground(False)
        self.buttonBox_Dialog_User_data_Save_Cancel.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 255);"))
        self.buttonBox_Dialog_User_data_Save_Cancel.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_Dialog_User_data_Save_Cancel.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.buttonBox_Dialog_User_data_Save_Cancel.setCenterButtons(False)
        self.buttonBox_Dialog_User_data_Save_Cancel.setObjectName(_fromUtf8("buttonBox_Dialog_User_data_Save_Cancel"))
        self.verticalLayout_2.addWidget(self.buttonBox_Dialog_User_data_Save_Cancel)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)

        self.retranslateUi(dialog_User_Data)
        QtCore.QObject.connect(self.buttonBox_Dialog_User_data_Save_Cancel, QtCore.SIGNAL(_fromUtf8("rejected()")), dialog_User_Data.reject)
        QtCore.QObject.connect(self.buttonBox_Dialog_User_data_Save_Cancel, QtCore.SIGNAL(_fromUtf8("accepted()")), dialog_User_Data.hide)
        QtCore.QMetaObject.connectSlotsByName(dialog_User_Data)

    def retranslateUi(self, dialog_User_Data):
        dialog_User_Data.setWindowTitle(_translate("dialog_User_Data", "Dialog", None))
        self.label_4.setText(_translate("dialog_User_Data", "Enter User ID or Name and Password:", None))
        self.label.setText(_translate("dialog_User_Data", "User ID", None))
        self.lineEdit__Dialog_User_data_User_ID.setPlaceholderText(_translate("dialog_User_Data", "Enter User ID here...", None))
        self.label_2.setText(_translate("dialog_User_Data", "User Name", None))
        self.lineEdit_Dialog_User_data_User_Name.setPlaceholderText(_translate("dialog_User_Data", "Search by name..", None))
        self.label_3.setText(_translate("dialog_User_Data", "   Password", None))
        self.lineEdit_Dialog_User_data_Password.setPlaceholderText(_translate("dialog_User_Data", "Enter Password..", None))
        self.checkBox_Widget_User_Data_Show_Password.setText(_translate("dialog_User_Data", "Show", None))
        self.pushButton__Dialog_User_data_Log_In.setText(_translate("dialog_User_Data", "Log in", None))
        self.textEdit_Dialog_User_data_Listing.setHtml(_translate("dialog_User_Data", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Monospace\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import background_icons_rc
