# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_WidgetComment_NoScroll.ui'
#
# Created: Tue Sep 29 22:38:24 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(937, 73)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tsq_frame_Comment = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_frame_Comment.sizePolicy().hasHeightForWidth())
        self.tsq_frame_Comment.setSizePolicy(sizePolicy)
        self.tsq_frame_Comment.setMinimumSize(QtCore.QSize(918, 50))
        self.tsq_frame_Comment.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tsq_frame_Comment.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(75, 75, 75, 0), stop:1 rgba(124, 124, 124, 0));\n"
""))
        self.tsq_frame_Comment.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_frame_Comment.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_frame_Comment.setLineWidth(2)
        self.tsq_frame_Comment.setMidLineWidth(0)
        self.tsq_frame_Comment.setObjectName(_fromUtf8("tsq_frame_Comment"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tsq_frame_Comment)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.line = QtGui.QFrame(self.tsq_frame_Comment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setMargin(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(2, -1, -1, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tsq_label_Comment_Useful = QtGui.QLabel(self.tsq_frame_Comment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_label_Comment_Useful.sizePolicy().hasHeightForWidth())
        self.tsq_label_Comment_Useful.setSizePolicy(sizePolicy)
        self.tsq_label_Comment_Useful.setMinimumSize(QtCore.QSize(16, 16))
        self.tsq_label_Comment_Useful.setMaximumSize(QtCore.QSize(16, 16))
        self.tsq_label_Comment_Useful.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tsq_label_Comment_Useful.setStyleSheet(_fromUtf8("background-color: rgba(0, 0, 0, 0);\n"
"background-image: url(:/comments_helpful/helpful.png);"))
        self.tsq_label_Comment_Useful.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Comment_Useful.setLineWidth(3)
        self.tsq_label_Comment_Useful.setText(_fromUtf8(""))
        self.tsq_label_Comment_Useful.setPixmap(QtGui.QPixmap(_fromUtf8(":/comments_helpful/helpful.png")))
        self.tsq_label_Comment_Useful.setAlignment(QtCore.Qt.AlignCenter)
        self.tsq_label_Comment_Useful.setObjectName(_fromUtf8("tsq_label_Comment_Useful"))
        self.verticalLayout.addWidget(self.tsq_label_Comment_Useful)
        self.tsq_label_Comment_Flag = QtGui.QLabel(self.tsq_frame_Comment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_label_Comment_Flag.sizePolicy().hasHeightForWidth())
        self.tsq_label_Comment_Flag.setSizePolicy(sizePolicy)
        self.tsq_label_Comment_Flag.setMinimumSize(QtCore.QSize(16, 16))
        self.tsq_label_Comment_Flag.setMaximumSize(QtCore.QSize(16, 16))
        self.tsq_label_Comment_Flag.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tsq_label_Comment_Flag.setStyleSheet(_fromUtf8("background-color: rgba(0, 0, 0, 0);\n"
"background-image: url(:/comments_deny/deny.png);"))
        self.tsq_label_Comment_Flag.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Comment_Flag.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_label_Comment_Flag.setLineWidth(0)
        self.tsq_label_Comment_Flag.setText(_fromUtf8(""))
        self.tsq_label_Comment_Flag.setPixmap(QtGui.QPixmap(_fromUtf8(":/comments_deny/deny.png")))
        self.tsq_label_Comment_Flag.setAlignment(QtCore.Qt.AlignCenter)
        self.tsq_label_Comment_Flag.setObjectName(_fromUtf8("tsq_label_Comment_Flag"))
        self.verticalLayout.addWidget(self.tsq_label_Comment_Flag)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tsq_label_Comment_Score = QtGui.QLabel(self.tsq_frame_Comment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_label_Comment_Score.sizePolicy().hasHeightForWidth())
        self.tsq_label_Comment_Score.setSizePolicy(sizePolicy)
        self.tsq_label_Comment_Score.setMinimumSize(QtCore.QSize(32, 32))
        self.tsq_label_Comment_Score.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(195, 148, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 148, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 148, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 148, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 148, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 148, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 148, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 148, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 148, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tsq_label_Comment_Score.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tsq_label_Comment_Score.setFont(font)
        self.tsq_label_Comment_Score.setStyleSheet(_fromUtf8("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(195, 148, 7);"))
        self.tsq_label_Comment_Score.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Comment_Score.setLineWidth(3)
        self.tsq_label_Comment_Score.setAlignment(QtCore.Qt.AlignCenter)
        self.tsq_label_Comment_Score.setObjectName(_fromUtf8("tsq_label_Comment_Score"))
        self.horizontalLayout.addWidget(self.tsq_label_Comment_Score)
        self.tsq_textBrowser_Comment_Body = QtGui.QTextBrowser(self.tsq_frame_Comment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_textBrowser_Comment_Body.sizePolicy().hasHeightForWidth())
        self.tsq_textBrowser_Comment_Body.setSizePolicy(sizePolicy)
        self.tsq_textBrowser_Comment_Body.setMinimumSize(QtCore.QSize(725, 35))
        self.tsq_textBrowser_Comment_Body.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tsq_textBrowser_Comment_Body.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tsq_textBrowser_Comment_Body.setFont(font)
        self.tsq_textBrowser_Comment_Body.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(225, 225, 225);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.tsq_textBrowser_Comment_Body.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_textBrowser_Comment_Body.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_textBrowser_Comment_Body.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tsq_textBrowser_Comment_Body.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tsq_textBrowser_Comment_Body.setObjectName(_fromUtf8("tsq_textBrowser_Comment_Body"))
        self.horizontalLayout.addWidget(self.tsq_textBrowser_Comment_Body)
        self.tsq_label_Comment_Author = QtGui.QLabel(self.tsq_frame_Comment)
        self.tsq_label_Comment_Author.setStyleSheet(_fromUtf8("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.tsq_label_Comment_Author.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Comment_Author.setObjectName(_fromUtf8("tsq_label_Comment_Author"))
        self.horizontalLayout.addWidget(self.tsq_label_Comment_Author)
        self.horizontalLayout.setStretch(2, 4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addWidget(self.tsq_frame_Comment)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.tsq_label_Comment_Score.setText(_translate("Form", "4", None))
        self.tsq_textBrowser_Comment_Body.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#00ff00;\">First Line</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#00ff00;\">Second Line</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#00ff00;\">Third Line</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#00ff00;\">Fourth Line</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#00ff00;\">Fifth Line</span></p></body></html>", None))
        self.tsq_label_Comment_Author.setText(_translate("Form", "Question Author", None))

import background_icons_rc
