# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_WidgetSingleQuestion.ui'
#
# Created: Tue Sep 29 22:38:30 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1054, 789)
        self.horizontalLayout_6 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tsq_frame_Question = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_frame_Question.sizePolicy().hasHeightForWidth())
        self.tsq_frame_Question.setSizePolicy(sizePolicy)
        self.tsq_frame_Question.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(98, 98, 98, 255), stop:1 rgba(199, 199, 199, 255));\n"
"background-color: rgba(255, 255, 255, 0);\n"
"background-color: rgb(80, 80, 80,0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(92, 13, 52, 0), stop:1 rgba(203, 121, 96,0));"))
        self.tsq_frame_Question.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_frame_Question.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_frame_Question.setObjectName(_fromUtf8("tsq_frame_Question"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tsq_frame_Question)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setMargin(9)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.tsq_pushButton_Question_UpVote = QtGui.QPushButton(self.tsq_frame_Question)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_pushButton_Question_UpVote.sizePolicy().hasHeightForWidth())
        self.tsq_pushButton_Question_UpVote.setSizePolicy(sizePolicy)
        self.tsq_pushButton_Question_UpVote.setMinimumSize(QtCore.QSize(32, 32))
        self.tsq_pushButton_Question_UpVote.setMaximumSize(QtCore.QSize(32, 32))
        self.tsq_pushButton_Question_UpVote.setStyleSheet(_fromUtf8(""))
        self.tsq_pushButton_Question_UpVote.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Vote Up/img/Vote_Up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tsq_pushButton_Question_UpVote.setIcon(icon)
        self.tsq_pushButton_Question_UpVote.setIconSize(QtCore.QSize(30, 30))
        self.tsq_pushButton_Question_UpVote.setObjectName(_fromUtf8("tsq_pushButton_Question_UpVote"))
        self.horizontalLayout.addWidget(self.tsq_pushButton_Question_UpVote)
        spacerItem3 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tsq_label_Question_Score = QtGui.QLabel(self.tsq_frame_Question)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tsq_label_Question_Score.setFont(font)
        self.tsq_label_Question_Score.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(129, 129, 129);\n"
"color: rgb(0, 0, 127);\n"
"color: rgb(195, 148, 7);\n"
""))
        self.tsq_label_Question_Score.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Question_Score.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_label_Question_Score.setAlignment(QtCore.Qt.AlignCenter)
        self.tsq_label_Question_Score.setMargin(1)
        self.tsq_label_Question_Score.setIndent(0)
        self.tsq_label_Question_Score.setObjectName(_fromUtf8("tsq_label_Question_Score"))
        self.verticalLayout.addWidget(self.tsq_label_Question_Score)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.tsq_pushButton_Question_DownVote = QtGui.QPushButton(self.tsq_frame_Question)
        self.tsq_pushButton_Question_DownVote.setMinimumSize(QtCore.QSize(32, 32))
        self.tsq_pushButton_Question_DownVote.setMaximumSize(QtCore.QSize(32, 32))
        self.tsq_pushButton_Question_DownVote.setStyleSheet(_fromUtf8(""))
        self.tsq_pushButton_Question_DownVote.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Vote Down/img/Vote_Down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tsq_pushButton_Question_DownVote.setIcon(icon1)
        self.tsq_pushButton_Question_DownVote.setIconSize(QtCore.QSize(30, 30))
        self.tsq_pushButton_Question_DownVote.setObjectName(_fromUtf8("tsq_pushButton_Question_DownVote"))
        self.horizontalLayout_2.addWidget(self.tsq_pushButton_Question_DownVote)
        spacerItem5 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem6 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.tsq_label_Question_Favorite = QtGui.QLabel(self.tsq_frame_Question)
        self.tsq_label_Question_Favorite.setMinimumSize(QtCore.QSize(30, 30))
        self.tsq_label_Question_Favorite.setMaximumSize(QtCore.QSize(30, 30))
        self.tsq_label_Question_Favorite.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tsq_label_Question_Favorite.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.tsq_label_Question_Favorite.setText(_fromUtf8(""))
        self.tsq_label_Question_Favorite.setObjectName(_fromUtf8("tsq_label_Question_Favorite"))
        self.horizontalLayout_3.addWidget(self.tsq_label_Question_Favorite)
        spacerItem7 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.setStretch(2, 8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.tsq_label_Question_Title = QtGui.QLabel(self.tsq_frame_Question)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tsq_label_Question_Title.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.tsq_label_Question_Title.setFont(font)
        self.tsq_label_Question_Title.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(195, 148, 7);\n"
"color: rgb(0, 170, 255);"))
        self.tsq_label_Question_Title.setTextFormat(QtCore.Qt.RichText)
        self.tsq_label_Question_Title.setScaledContents(False)
        self.tsq_label_Question_Title.setWordWrap(True)
        self.tsq_label_Question_Title.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.tsq_label_Question_Title.setObjectName(_fromUtf8("tsq_label_Question_Title"))
        self.verticalLayout_9.addWidget(self.tsq_label_Question_Title)
        self.line_6 = QtGui.QFrame(self.tsq_frame_Question)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_9.addWidget(self.line_6)
        self.tsq_textBrowser_Question_Body = QtGui.QTextBrowser(self.tsq_frame_Question)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_textBrowser_Question_Body.sizePolicy().hasHeightForWidth())
        self.tsq_textBrowser_Question_Body.setSizePolicy(sizePolicy)
        self.tsq_textBrowser_Question_Body.setMinimumSize(QtCore.QSize(920, 0))
        self.tsq_textBrowser_Question_Body.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tsq_textBrowser_Question_Body.setSizeIncrement(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tsq_textBrowser_Question_Body.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tsq_textBrowser_Question_Body.setFont(font)
        self.tsq_textBrowser_Question_Body.setStyleSheet(_fromUtf8("background-color: rgb(63, 63, 63, 120);\n"
"color: rgb(225, 225, 225);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgba(255, 255, 255, 0);\n"
""))
        self.tsq_textBrowser_Question_Body.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_textBrowser_Question_Body.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_textBrowser_Question_Body.setLineWidth(1)
        self.tsq_textBrowser_Question_Body.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tsq_textBrowser_Question_Body.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tsq_textBrowser_Question_Body.setAutoFormatting(QtGui.QTextEdit.AutoNone)
        self.tsq_textBrowser_Question_Body.setDocumentTitle(_fromUtf8(""))
        self.tsq_textBrowser_Question_Body.setReadOnly(True)
        self.tsq_textBrowser_Question_Body.setAcceptRichText(True)
        self.tsq_textBrowser_Question_Body.setCursorWidth(1)
        self.tsq_textBrowser_Question_Body.setOpenExternalLinks(True)
        self.tsq_textBrowser_Question_Body.setObjectName(_fromUtf8("tsq_textBrowser_Question_Body"))
        self.verticalLayout_9.addWidget(self.tsq_textBrowser_Question_Body)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem9)
        self.tsq_frame_Question_Owner = QtGui.QFrame(self.tsq_frame_Question)
        self.tsq_frame_Question_Owner.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 0);\n"
"background-color: rgb(140, 140, 140);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(39, 39, 177, 255));"))
        self.tsq_frame_Question_Owner.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_frame_Question_Owner.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_frame_Question_Owner.setLineWidth(0)
        self.tsq_frame_Question_Owner.setObjectName(_fromUtf8("tsq_frame_Question_Owner"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.tsq_frame_Question_Owner)
        self.horizontalLayout_21.setMargin(1)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setMargin(4)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.tsq_label_Question_Owner_Profile = QtGui.QLabel(self.tsq_frame_Question_Owner)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_label_Question_Owner_Profile.sizePolicy().hasHeightForWidth())
        self.tsq_label_Question_Owner_Profile.setSizePolicy(sizePolicy)
        self.tsq_label_Question_Owner_Profile.setMinimumSize(QtCore.QSize(48, 48))
        self.tsq_label_Question_Owner_Profile.setMaximumSize(QtCore.QSize(48, 48))
        self.tsq_label_Question_Owner_Profile.setStyleSheet(_fromUtf8(""))
        self.tsq_label_Question_Owner_Profile.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Question_Owner_Profile.setText(_fromUtf8(""))
        self.tsq_label_Question_Owner_Profile.setObjectName(_fromUtf8("tsq_label_Question_Owner_Profile"))
        self.horizontalLayout_20.addWidget(self.tsq_label_Question_Owner_Profile)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(12)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.tsq_label_Question_Owner_Name = QtGui.QLabel(self.tsq_frame_Question_Owner)
        self.tsq_label_Question_Owner_Name.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.tsq_label_Question_Owner_Name.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Question_Owner_Name.setObjectName(_fromUtf8("tsq_label_Question_Owner_Name"))
        self.horizontalLayout_18.addWidget(self.tsq_label_Question_Owner_Name)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.tsq_label_Question_Owner_Repuation = QtGui.QLabel(self.tsq_frame_Question_Owner)
        self.tsq_label_Question_Owner_Repuation.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.tsq_label_Question_Owner_Repuation.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Question_Owner_Repuation.setObjectName(_fromUtf8("tsq_label_Question_Owner_Repuation"))
        self.horizontalLayout_19.addWidget(self.tsq_label_Question_Owner_Repuation)
        self.label = QtGui.QLabel(self.tsq_frame_Question_Owner)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(10, 10))
        self.label.setMaximumSize(QtCore.QSize(10, 10))
        self.label.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.528302 rgba(255, 215, 0, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_19.addWidget(self.label)
        self.tsq_label_Question_Owner_Gold = QtGui.QLabel(self.tsq_frame_Question_Owner)
        self.tsq_label_Question_Owner_Gold.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.tsq_label_Question_Owner_Gold.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Question_Owner_Gold.setLineWidth(1)
        self.tsq_label_Question_Owner_Gold.setObjectName(_fromUtf8("tsq_label_Question_Owner_Gold"))
        self.horizontalLayout_19.addWidget(self.tsq_label_Question_Owner_Gold)
        self.label_2 = QtGui.QLabel(self.tsq_frame_Question_Owner)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(10, 10))
        self.label_2.setMaximumSize(QtCore.QSize(10, 10))
        self.label_2.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.528302 rgba(192, 192, 192, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_19.addWidget(self.label_2)
        self.tsq_label_Question_Owner_Silver = QtGui.QLabel(self.tsq_frame_Question_Owner)
        self.tsq_label_Question_Owner_Silver.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.tsq_label_Question_Owner_Silver.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Question_Owner_Silver.setLineWidth(1)
        self.tsq_label_Question_Owner_Silver.setObjectName(_fromUtf8("tsq_label_Question_Owner_Silver"))
        self.horizontalLayout_19.addWidget(self.tsq_label_Question_Owner_Silver)
        self.label_4 = QtGui.QLabel(self.tsq_frame_Question_Owner)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(10, 10))
        self.label_4.setMaximumSize(QtCore.QSize(10, 10))
        self.label_4.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.528302 rgba(205, 127, 50, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.label_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_19.addWidget(self.label_4)
        self.tsq_label_Question_Owner_Bronze = QtGui.QLabel(self.tsq_frame_Question_Owner)
        self.tsq_label_Question_Owner_Bronze.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.tsq_label_Question_Owner_Bronze.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Question_Owner_Bronze.setLineWidth(1)
        self.tsq_label_Question_Owner_Bronze.setObjectName(_fromUtf8("tsq_label_Question_Owner_Bronze"))
        self.horizontalLayout_19.addWidget(self.tsq_label_Question_Owner_Bronze)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20.addLayout(self.verticalLayout_8)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_22.addWidget(self.tsq_frame_Question_Owner)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem11)
        self.horizontalLayout_22.setStretch(0, 3)
        self.horizontalLayout_22.setStretch(2, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_22)
        self.tsq_listWidget_Question_Comments = QtGui.QListWidget(self.tsq_frame_Question)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_listWidget_Question_Comments.sizePolicy().hasHeightForWidth())
        self.tsq_listWidget_Question_Comments.setSizePolicy(sizePolicy)
        self.tsq_listWidget_Question_Comments.setMinimumSize(QtCore.QSize(920, 50))
        self.tsq_listWidget_Question_Comments.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tsq_listWidget_Question_Comments.setStyleSheet(_fromUtf8("background-color: rgb(63, 63, 63, 120);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.tsq_listWidget_Question_Comments.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_listWidget_Question_Comments.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_listWidget_Question_Comments.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tsq_listWidget_Question_Comments.setAutoScroll(False)
        self.tsq_listWidget_Question_Comments.setTabKeyNavigation(False)
        self.tsq_listWidget_Question_Comments.setProperty("showDropIndicator", False)
        self.tsq_listWidget_Question_Comments.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tsq_listWidget_Question_Comments.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tsq_listWidget_Question_Comments.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tsq_listWidget_Question_Comments.setMovement(QtGui.QListView.Free)
        self.tsq_listWidget_Question_Comments.setResizeMode(QtGui.QListView.Fixed)
        self.tsq_listWidget_Question_Comments.setUniformItemSizes(True)
        self.tsq_listWidget_Question_Comments.setObjectName(_fromUtf8("tsq_listWidget_Question_Comments"))
        self.verticalLayout_9.addWidget(self.tsq_listWidget_Question_Comments)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(5)
        self.horizontalLayout_23.setContentsMargins(-1, -1, 5, -1)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.tsq_textEdit_Question_Comment_Box = QtGui.QTextEdit(self.tsq_frame_Question)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_textEdit_Question_Comment_Box.sizePolicy().hasHeightForWidth())
        self.tsq_textEdit_Question_Comment_Box.setSizePolicy(sizePolicy)
        self.tsq_textEdit_Question_Comment_Box.setMinimumSize(QtCore.QSize(800, 40))
        self.tsq_textEdit_Question_Comment_Box.setMaximumSize(QtCore.QSize(16777215, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tsq_textEdit_Question_Comment_Box.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.tsq_textEdit_Question_Comment_Box.setFont(font)
        self.tsq_textEdit_Question_Comment_Box.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tsq_textEdit_Question_Comment_Box.setStyleSheet(_fromUtf8("background-color: rgb(63, 63, 63, 120);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.tsq_textEdit_Question_Comment_Box.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_textEdit_Question_Comment_Box.setObjectName(_fromUtf8("tsq_textEdit_Question_Comment_Box"))
        self.horizontalLayout_23.addWidget(self.tsq_textEdit_Question_Comment_Box)
        self.tsq_label_Question_Comment_Post = QtGui.QLabel(self.tsq_frame_Question)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_label_Question_Comment_Post.sizePolicy().hasHeightForWidth())
        self.tsq_label_Question_Comment_Post.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.tsq_label_Question_Comment_Post.setFont(font)
        self.tsq_label_Question_Comment_Post.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tsq_label_Question_Comment_Post.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 177);"))
        self.tsq_label_Question_Comment_Post.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_label_Question_Comment_Post.setObjectName(_fromUtf8("tsq_label_Question_Comment_Post"))
        self.horizontalLayout_23.addWidget(self.tsq_label_Question_Comment_Post)
        self.verticalLayout_9.addLayout(self.horizontalLayout_23)
        self.verticalLayout_9.setStretch(2, 5)
        self.verticalLayout_9.setStretch(4, 2)
        self.verticalLayout_9.setStretch(5, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 15)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem12 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem12)
        self.tsq_label_Answer_Count = QtGui.QLabel(self.tsq_frame_Question)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.tsq_label_Answer_Count.setFont(font)
        self.tsq_label_Answer_Count.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(195, 148, 7);\n"
"color: rgb(255, 255, 255);\n"
""))
        self.tsq_label_Answer_Count.setObjectName(_fromUtf8("tsq_label_Answer_Count"))
        self.verticalLayout_3.addWidget(self.tsq_label_Answer_Count)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_6.addWidget(self.tsq_frame_Question)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.tsq_label_Question_Score.setText(_translate("Form", "9999", None))
        self.tsq_label_Question_Title.setText(_translate("Form", "Question Title goes here", None))
        self.tsq_textBrowser_Question_Body.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Monospace\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii</span></p></body></html>", None))
        self.tsq_label_Question_Owner_Name.setText(_translate("Form", "Khalil Ammour @ Sep, 13th", None))
        self.tsq_label_Question_Owner_Repuation.setText(_translate("Form", "1624", None))
        self.tsq_label_Question_Owner_Gold.setText(_translate("Form", "0", None))
        self.tsq_label_Question_Owner_Silver.setText(_translate("Form", "1", None))
        self.tsq_label_Question_Owner_Bronze.setText(_translate("Form", "14", None))
        self.tsq_label_Question_Comment_Post.setText(_translate("Form", "Comment", None))
        self.tsq_label_Answer_Count.setText(_translate("Form", "2 Answers", None))

import background_icons_rc
