# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_WidgetAnswer.ui'
#
# Created: Tue Sep 29 22:38:36 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1114, 636)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout_3 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tsq_frame_Answer = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_frame_Answer.sizePolicy().hasHeightForWidth())
        self.tsq_frame_Answer.setSizePolicy(sizePolicy)
        self.tsq_frame_Answer.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(98, 98, 98, 255), stop:1 rgba(199, 199, 199, 255));\n"
"background-color: rgba(255, 255, 255, 0);\n"
"background-color: rgb(97, 48, 72,0);"))
        self.tsq_frame_Answer.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_frame_Answer.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_frame_Answer.setObjectName(_fromUtf8("tsq_frame_Answer"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tsq_frame_Answer)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setMargin(9)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.line = QtGui.QFrame(self.tsq_frame_Answer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 48, 72, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 48, 72, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 48, 72, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 48, 72, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 48, 72, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 48, 72, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 48, 72, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 48, 72, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 48, 72, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.line.setPalette(palette)
        self.line.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);"))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.tsq_pushButton_Answer_UpVote = QtGui.QPushButton(self.tsq_frame_Answer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_pushButton_Answer_UpVote.sizePolicy().hasHeightForWidth())
        self.tsq_pushButton_Answer_UpVote.setSizePolicy(sizePolicy)
        self.tsq_pushButton_Answer_UpVote.setMinimumSize(QtCore.QSize(32, 32))
        self.tsq_pushButton_Answer_UpVote.setMaximumSize(QtCore.QSize(32, 32))
        self.tsq_pushButton_Answer_UpVote.setStyleSheet(_fromUtf8(""))
        self.tsq_pushButton_Answer_UpVote.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Vote Up/img/Vote_Up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tsq_pushButton_Answer_UpVote.setIcon(icon)
        self.tsq_pushButton_Answer_UpVote.setIconSize(QtCore.QSize(30, 30))
        self.tsq_pushButton_Answer_UpVote.setObjectName(_fromUtf8("tsq_pushButton_Answer_UpVote"))
        self.horizontalLayout.addWidget(self.tsq_pushButton_Answer_UpVote)
        spacerItem2 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tsq_label_Answer_Score = QtGui.QLabel(self.tsq_frame_Answer)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tsq_label_Answer_Score.setFont(font)
        self.tsq_label_Answer_Score.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(129, 129, 129);\n"
"color: rgb(0, 0, 127);\n"
"color: rgb(195, 148, 7);"))
        self.tsq_label_Answer_Score.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Answer_Score.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_label_Answer_Score.setAlignment(QtCore.Qt.AlignCenter)
        self.tsq_label_Answer_Score.setMargin(1)
        self.tsq_label_Answer_Score.setIndent(0)
        self.tsq_label_Answer_Score.setObjectName(_fromUtf8("tsq_label_Answer_Score"))
        self.verticalLayout.addWidget(self.tsq_label_Answer_Score)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.tsq_pushButton_Answer_DownVote = QtGui.QPushButton(self.tsq_frame_Answer)
        self.tsq_pushButton_Answer_DownVote.setMinimumSize(QtCore.QSize(32, 32))
        self.tsq_pushButton_Answer_DownVote.setMaximumSize(QtCore.QSize(32, 32))
        self.tsq_pushButton_Answer_DownVote.setStyleSheet(_fromUtf8(""))
        self.tsq_pushButton_Answer_DownVote.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Vote Down/img/Vote_Down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tsq_pushButton_Answer_DownVote.setIcon(icon1)
        self.tsq_pushButton_Answer_DownVote.setIconSize(QtCore.QSize(30, 30))
        self.tsq_pushButton_Answer_DownVote.setObjectName(_fromUtf8("tsq_pushButton_Answer_DownVote"))
        self.horizontalLayout_2.addWidget(self.tsq_pushButton_Answer_DownVote)
        spacerItem4 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.tsq_label_Answer_Accepted = QtGui.QLabel(self.tsq_frame_Answer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_label_Answer_Accepted.sizePolicy().hasHeightForWidth())
        self.tsq_label_Answer_Accepted.setSizePolicy(sizePolicy)
        self.tsq_label_Answer_Accepted.setMinimumSize(QtCore.QSize(48, 48))
        self.tsq_label_Answer_Accepted.setMaximumSize(QtCore.QSize(48, 48))
        self.tsq_label_Answer_Accepted.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.tsq_label_Answer_Accepted.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Answer_Accepted.setMidLineWidth(0)
        self.tsq_label_Answer_Accepted.setText(_fromUtf8(""))
        self.tsq_label_Answer_Accepted.setAlignment(QtCore.Qt.AlignCenter)
        self.tsq_label_Answer_Accepted.setIndent(0)
        self.tsq_label_Answer_Accepted.setObjectName(_fromUtf8("tsq_label_Answer_Accepted"))
        self.horizontalLayout_6.addWidget(self.tsq_label_Answer_Accepted)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.setStretch(2, 8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_9.addItem(spacerItem9)
        self.tsq_textBrowser_Answer_Body = QtGui.QTextBrowser(self.tsq_frame_Answer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_textBrowser_Answer_Body.sizePolicy().hasHeightForWidth())
        self.tsq_textBrowser_Answer_Body.setSizePolicy(sizePolicy)
        self.tsq_textBrowser_Answer_Body.setMinimumSize(QtCore.QSize(920, 0))
        self.tsq_textBrowser_Answer_Body.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tsq_textBrowser_Answer_Body.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.tsq_textBrowser_Answer_Body.setFont(font)
        self.tsq_textBrowser_Answer_Body.setStyleSheet(_fromUtf8("background-color: rgb(216, 216, 216);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgb(53, 53, 53,120);\n"
"color: rgb(225, 225, 225);"))
        self.tsq_textBrowser_Answer_Body.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_textBrowser_Answer_Body.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_textBrowser_Answer_Body.setLineWidth(1)
        self.tsq_textBrowser_Answer_Body.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tsq_textBrowser_Answer_Body.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tsq_textBrowser_Answer_Body.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.tsq_textBrowser_Answer_Body.setLineWrapColumnOrWidth(0)
        self.tsq_textBrowser_Answer_Body.setOpenExternalLinks(True)
        self.tsq_textBrowser_Answer_Body.setObjectName(_fromUtf8("tsq_textBrowser_Answer_Body"))
        self.verticalLayout_9.addWidget(self.tsq_textBrowser_Answer_Body)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem10)
        self.tsq_frame_Answer_Owner = QtGui.QFrame(self.tsq_frame_Answer)
        self.tsq_frame_Answer_Owner.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 0);\n"
"background-color: rgb(140, 140, 140);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(39, 39, 177, 255));"))
        self.tsq_frame_Answer_Owner.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_frame_Answer_Owner.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_frame_Answer_Owner.setLineWidth(0)
        self.tsq_frame_Answer_Owner.setObjectName(_fromUtf8("tsq_frame_Answer_Owner"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.tsq_frame_Answer_Owner)
        self.horizontalLayout_21.setMargin(1)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_20.setMargin(4)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.tsq_label_Answer_Owner_Profile = QtGui.QLabel(self.tsq_frame_Answer_Owner)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_label_Answer_Owner_Profile.sizePolicy().hasHeightForWidth())
        self.tsq_label_Answer_Owner_Profile.setSizePolicy(sizePolicy)
        self.tsq_label_Answer_Owner_Profile.setMinimumSize(QtCore.QSize(48, 48))
        self.tsq_label_Answer_Owner_Profile.setMaximumSize(QtCore.QSize(48, 48))
        self.tsq_label_Answer_Owner_Profile.setStyleSheet(_fromUtf8(""))
        self.tsq_label_Answer_Owner_Profile.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Answer_Owner_Profile.setText(_fromUtf8(""))
        self.tsq_label_Answer_Owner_Profile.setObjectName(_fromUtf8("tsq_label_Answer_Owner_Profile"))
        self.horizontalLayout_20.addWidget(self.tsq_label_Answer_Owner_Profile)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(12)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.tsq_label_Answer_Owner_Name = QtGui.QLabel(self.tsq_frame_Answer_Owner)
        self.tsq_label_Answer_Owner_Name.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.tsq_label_Answer_Owner_Name.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Answer_Owner_Name.setObjectName(_fromUtf8("tsq_label_Answer_Owner_Name"))
        self.horizontalLayout_18.addWidget(self.tsq_label_Answer_Owner_Name)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.tsq_label_Answer_Owner_Repuation = QtGui.QLabel(self.tsq_frame_Answer_Owner)
        self.tsq_label_Answer_Owner_Repuation.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.tsq_label_Answer_Owner_Repuation.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Answer_Owner_Repuation.setObjectName(_fromUtf8("tsq_label_Answer_Owner_Repuation"))
        self.horizontalLayout_19.addWidget(self.tsq_label_Answer_Owner_Repuation)
        self.label = QtGui.QLabel(self.tsq_frame_Answer_Owner)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(10, 10))
        self.label.setMaximumSize(QtCore.QSize(10, 10))
        self.label.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.528302 rgba(255, 215, 0, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_19.addWidget(self.label)
        self.tsq_label_Answer_Owner_Gold = QtGui.QLabel(self.tsq_frame_Answer_Owner)
        self.tsq_label_Answer_Owner_Gold.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.tsq_label_Answer_Owner_Gold.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Answer_Owner_Gold.setLineWidth(1)
        self.tsq_label_Answer_Owner_Gold.setObjectName(_fromUtf8("tsq_label_Answer_Owner_Gold"))
        self.horizontalLayout_19.addWidget(self.tsq_label_Answer_Owner_Gold)
        self.label_2 = QtGui.QLabel(self.tsq_frame_Answer_Owner)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(10, 10))
        self.label_2.setMaximumSize(QtCore.QSize(10, 10))
        self.label_2.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.528302 rgba(192, 192, 192, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_19.addWidget(self.label_2)
        self.tsq_label_Answer_Owner_Silver = QtGui.QLabel(self.tsq_frame_Answer_Owner)
        self.tsq_label_Answer_Owner_Silver.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.tsq_label_Answer_Owner_Silver.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Answer_Owner_Silver.setLineWidth(1)
        self.tsq_label_Answer_Owner_Silver.setObjectName(_fromUtf8("tsq_label_Answer_Owner_Silver"))
        self.horizontalLayout_19.addWidget(self.tsq_label_Answer_Owner_Silver)
        self.label_4 = QtGui.QLabel(self.tsq_frame_Answer_Owner)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(10, 10))
        self.label_4.setMaximumSize(QtCore.QSize(10, 10))
        self.label_4.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.528302 rgba(205, 127, 50, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.label_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_19.addWidget(self.label_4)
        self.tsq_label_Answer_Owner_Bronze = QtGui.QLabel(self.tsq_frame_Answer_Owner)
        self.tsq_label_Answer_Owner_Bronze.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);"))
        self.tsq_label_Answer_Owner_Bronze.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Answer_Owner_Bronze.setLineWidth(1)
        self.tsq_label_Answer_Owner_Bronze.setObjectName(_fromUtf8("tsq_label_Answer_Owner_Bronze"))
        self.horizontalLayout_19.addWidget(self.tsq_label_Answer_Owner_Bronze)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem11)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20.addLayout(self.verticalLayout_8)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_22.addWidget(self.tsq_frame_Answer_Owner)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem12)
        self.horizontalLayout_22.setStretch(0, 3)
        self.horizontalLayout_22.setStretch(2, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_22)
        self.tsq_listWidget_Answer_Comments = QtGui.QListWidget(self.tsq_frame_Answer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_listWidget_Answer_Comments.sizePolicy().hasHeightForWidth())
        self.tsq_listWidget_Answer_Comments.setSizePolicy(sizePolicy)
        self.tsq_listWidget_Answer_Comments.setMinimumSize(QtCore.QSize(920, 50))
        self.tsq_listWidget_Answer_Comments.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tsq_listWidget_Answer_Comments.setSizeIncrement(QtCore.QSize(0, 0))
        self.tsq_listWidget_Answer_Comments.setStyleSheet(_fromUtf8("background-color: rgb(63, 63, 63,120);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.tsq_listWidget_Answer_Comments.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_listWidget_Answer_Comments.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_listWidget_Answer_Comments.setAutoScroll(False)
        self.tsq_listWidget_Answer_Comments.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tsq_listWidget_Answer_Comments.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tsq_listWidget_Answer_Comments.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tsq_listWidget_Answer_Comments.setMovement(QtGui.QListView.Free)
        self.tsq_listWidget_Answer_Comments.setUniformItemSizes(True)
        self.tsq_listWidget_Answer_Comments.setObjectName(_fromUtf8("tsq_listWidget_Answer_Comments"))
        self.verticalLayout_9.addWidget(self.tsq_listWidget_Answer_Comments)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(5)
        self.horizontalLayout_23.setContentsMargins(-1, -1, 5, -1)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.tsq_textEdit_Answer_Comment_Box = QtGui.QTextEdit(self.tsq_frame_Answer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_textEdit_Answer_Comment_Box.sizePolicy().hasHeightForWidth())
        self.tsq_textEdit_Answer_Comment_Box.setSizePolicy(sizePolicy)
        self.tsq_textEdit_Answer_Comment_Box.setMinimumSize(QtCore.QSize(0, 40))
        self.tsq_textEdit_Answer_Comment_Box.setMaximumSize(QtCore.QSize(16777215, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 63, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tsq_textEdit_Answer_Comment_Box.setPalette(palette)
        self.tsq_textEdit_Answer_Comment_Box.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tsq_textEdit_Answer_Comment_Box.setStyleSheet(_fromUtf8("background-color: rgb(63, 63, 63,120);\n"
"color: rgb(0, 255, 0);\n"
"color: rgb(225, 225, 225);\n"
"border-color: rgba(255, 255, 255, 0);"))
        self.tsq_textEdit_Answer_Comment_Box.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_textEdit_Answer_Comment_Box.setObjectName(_fromUtf8("tsq_textEdit_Answer_Comment_Box"))
        self.horizontalLayout_23.addWidget(self.tsq_textEdit_Answer_Comment_Box)
        self.tsq_label_Answer_Comment_Post = QtGui.QLabel(self.tsq_frame_Answer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsq_label_Answer_Comment_Post.sizePolicy().hasHeightForWidth())
        self.tsq_label_Answer_Comment_Post.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tsq_label_Answer_Comment_Post.setFont(font)
        self.tsq_label_Answer_Comment_Post.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tsq_label_Answer_Comment_Post.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 177);"))
        self.tsq_label_Answer_Comment_Post.setFrameShape(QtGui.QFrame.NoFrame)
        self.tsq_label_Answer_Comment_Post.setFrameShadow(QtGui.QFrame.Plain)
        self.tsq_label_Answer_Comment_Post.setLineWidth(1)
        self.tsq_label_Answer_Comment_Post.setMidLineWidth(0)
        self.tsq_label_Answer_Comment_Post.setObjectName(_fromUtf8("tsq_label_Answer_Comment_Post"))
        self.horizontalLayout_23.addWidget(self.tsq_label_Answer_Comment_Post)
        self.verticalLayout_9.addLayout(self.horizontalLayout_23)
        self.verticalLayout_9.setStretch(1, 5)
        self.verticalLayout_9.setStretch(3, 2)
        self.verticalLayout_9.setStretch(4, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 15)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.setStretch(0, 9)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.addWidget(self.tsq_frame_Answer)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.tsq_label_Answer_Score.setText(_translate("Form", "9999", None))
        self.tsq_textBrowser_Answer_Body.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#e1e1e1;\">Why it\'s limited to 65535, which is maximum number, that could be represented by 16 bits? </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#e1e1e1;\">Its atleast 16 bit. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:40px; margin-right:40px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#e1e1e1;\">According to the 1999 ISO C standard (C99), size_t is an unsigned integer type of at least 16 bit (see sections 7.17 and 7.18.3). </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#e1e1e1;\">Why use </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">size_t</span><span style=\" font-size:11pt; color:#e1e1e1;\"> ? </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">size_t</span><span style=\" font-size:11pt; color:#e1e1e1;\"> is a type guaranteed to hold any array index. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">size_t</span><span style=\" font-size:11pt; color:#e1e1e1;\"> can be any of (and also can be anything else other than these) </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned char</span><span style=\" font-size:11pt; color:#e1e1e1;\">, </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned short</span><span style=\" font-size:11pt; color:#e1e1e1;\">, </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned int</span><span style=\" font-size:11pt; color:#e1e1e1;\">, </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned long</span><span style=\" font-size:11pt; color:#e1e1e1;\"> or </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned long long</span><span style=\" font-size:11pt; color:#e1e1e1;\">, depending on the implementation. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#e1e1e1;\">And to use </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned int</span><span style=\" font-size:11pt; color:#e1e1e1;\"> or </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned long</span><span style=\" font-size:11pt; color:#e1e1e1;\"> in place of </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">size_t</span><span style=\" font-size:11pt; color:#e1e1e1;\"> ,reason is similar that they are not the only unsigned integral types. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#e1e1e1;\">Its purpose is to relieve the programmer from having to worry about which of the predefined types is used to represent sizes. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#e1e1e1;\">On one system, it might make sense to use </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned int</span><span style=\" font-size:11pt; color:#e1e1e1;\"> to represent sizes; on another, it might make more sense to use </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned long</span><span style=\" font-size:11pt; color:#e1e1e1;\"> or </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned long long</span><span style=\" font-size:11pt; color:#e1e1e1;\">. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#e1e1e1;\">So using </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">size_t</span><span style=\" font-size:11pt; color:#e1e1e1;\"> adds the advantage that code is likely to be more portable. Why it\'s limited to 65535, which is maximum number, that could be represented by 16 bits? </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#e1e1e1;\">Its atleast 16 bit. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:40px; margin-right:40px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#e1e1e1;\">According to the 1999 ISO C standard (C99), size_t is an unsigned integer type of at least 16 bit (see sections 7.17 and 7.18.3). </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#e1e1e1;\">Why use </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">size_t</span><span style=\" font-size:11pt; color:#e1e1e1;\"> ? </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">size_t</span><span style=\" font-size:11pt; color:#e1e1e1;\"> is a type guaranteed to hold any array index. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">size_t</span><span style=\" font-size:11pt; color:#e1e1e1;\"> can be any of (and also can be anything else other than these) </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned char</span><span style=\" font-size:11pt; color:#e1e1e1;\">, </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned short</span><span style=\" font-size:11pt; color:#e1e1e1;\">, </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned int</span><span style=\" font-size:11pt; color:#e1e1e1;\">, </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned long</span><span style=\" font-size:11pt; color:#e1e1e1;\"> or </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned long long</span><span style=\" font-size:11pt; color:#e1e1e1;\">, depending on the implementation. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#e1e1e1;\">And to use </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned int</span><span style=\" font-size:11pt; color:#e1e1e1;\"> or </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned long</span><span style=\" font-size:11pt; color:#e1e1e1;\"> in place of </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">size_t</span><span style=\" font-size:11pt; color:#e1e1e1;\"> ,reason is similar that they are not the only unsigned integral types. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#e1e1e1;\">Its purpose is to relieve the programmer from having to worry about which of the predefined types is used to represent sizes. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#e1e1e1;\">On one system, it might make sense to use </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned int</span><span style=\" font-size:11pt; color:#e1e1e1;\"> to represent sizes; on another, it might make more sense to use </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned long</span><span style=\" font-size:11pt; color:#e1e1e1;\"> or </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">unsigned long long</span><span style=\" font-size:11pt; color:#e1e1e1;\">. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#e1e1e1;\">So using </span><span style=\" font-family:\'Courier New,courier\'; font-size:11pt; color:#e1e1e1;\">size_t</span><span style=\" font-size:11pt; color:#e1e1e1;\"> adds the advantage that code is likely to be more portable. </span></p></body></html>", None))
        self.tsq_label_Answer_Owner_Name.setText(_translate("Form", "Khalil Ammour @ Sep, 13th", None))
        self.tsq_label_Answer_Owner_Repuation.setText(_translate("Form", "1624", None))
        self.tsq_label_Answer_Owner_Gold.setText(_translate("Form", "0", None))
        self.tsq_label_Answer_Owner_Silver.setText(_translate("Form", "1", None))
        self.tsq_label_Answer_Owner_Bronze.setText(_translate("Form", "14", None))
        self.tsq_label_Answer_Comment_Post.setText(_translate("Form", "Comment", None))

import background_icons_rc
