# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_WidgetQuestion.ui'
#
# Created: Sat Oct  3 00:25:49 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FORM(object):
    def setupUi(self, FORM):
        FORM.setObjectName(_fromUtf8("FORM"))
        FORM.resize(865, 144)
        self.wq_Frame = QtGui.QFrame(FORM)
        self.wq_Frame.setGeometry(QtCore.QRect(20, 30, 830, 100))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wq_Frame.sizePolicy().hasHeightForWidth())
        self.wq_Frame.setSizePolicy(sizePolicy)
        self.wq_Frame.setMinimumSize(QtCore.QSize(830, 100))
        self.wq_Frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.wq_Frame.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(75, 75, 75, 255), stop:1 rgba(124, 124, 124, 255));\n"
""))
        self.wq_Frame.setFrameShape(QtGui.QFrame.Box)
        self.wq_Frame.setFrameShadow(QtGui.QFrame.Plain)
        self.wq_Frame.setLineWidth(2)
        self.wq_Frame.setMidLineWidth(0)
        self.wq_Frame.setObjectName(_fromUtf8("wq_Frame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.wq_Frame)
        self.verticalLayout_4.setMargin(1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.wq_label_Site = QtGui.QLabel(self.wq_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wq_label_Site.sizePolicy().hasHeightForWidth())
        self.wq_label_Site.setSizePolicy(sizePolicy)
        self.wq_label_Site.setMinimumSize(QtCore.QSize(32, 32))
        self.wq_label_Site.setMaximumSize(QtCore.QSize(32, 32))
        self.wq_label_Site.setStyleSheet(_fromUtf8("background-color: rgba(0, 0, 0, 0);"))
        self.wq_label_Site.setObjectName(_fromUtf8("wq_label_Site"))
        self.horizontalLayout_2.addWidget(self.wq_label_Site)
        self.wq_label_Title = QLabelCustom(self.wq_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wq_label_Title.sizePolicy().hasHeightForWidth())
        self.wq_label_Title.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(101, 219, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 219, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 219, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 219, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 219, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 219, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 219, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 219, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 219, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.wq_label_Title.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.wq_label_Title.setFont(font)
        self.wq_label_Title.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.wq_label_Title.setMouseTracking(True)
        self.wq_label_Title.setStyleSheet(_fromUtf8("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(101, 219, 255);"))
        self.wq_label_Title.setFrameShape(QtGui.QFrame.NoFrame)
        self.wq_label_Title.setTextFormat(QtCore.Qt.RichText)
        self.wq_label_Title.setScaledContents(False)
        self.wq_label_Title.setOpenExternalLinks(False)
        self.wq_label_Title.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.wq_label_Title.setObjectName(_fromUtf8("wq_label_Title"))
        self.horizontalLayout_2.addWidget(self.wq_label_Title)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.wq_label_Question_State = QtGui.QLabel(self.wq_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wq_label_Question_State.sizePolicy().hasHeightForWidth())
        self.wq_label_Question_State.setSizePolicy(sizePolicy)
        self.wq_label_Question_State.setMinimumSize(QtCore.QSize(50, 50))
        self.wq_label_Question_State.setMaximumSize(QtCore.QSize(50, 50))
        self.wq_label_Question_State.setStyleSheet(_fromUtf8("background-color: rgba(0, 0, 0, 0);"))
        self.wq_label_Question_State.setFrameShape(QtGui.QFrame.NoFrame)
        self.wq_label_Question_State.setFrameShadow(QtGui.QFrame.Plain)
        self.wq_label_Question_State.setAlignment(QtCore.Qt.AlignCenter)
        self.wq_label_Question_State.setObjectName(_fromUtf8("wq_label_Question_State"))
        self.horizontalLayout_3.addWidget(self.wq_label_Question_State)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.wq_label_body = QtGui.QLabel(self.wq_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wq_label_body.sizePolicy().hasHeightForWidth())
        self.wq_label_body.setSizePolicy(sizePolicy)
        self.wq_label_body.setStyleSheet(_fromUtf8("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.wq_label_body.setFrameShape(QtGui.QFrame.NoFrame)
        self.wq_label_body.setScaledContents(False)
        self.wq_label_body.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.wq_label_body.setWordWrap(False)
        self.wq_label_body.setObjectName(_fromUtf8("wq_label_body"))
        self.verticalLayout_2.addWidget(self.wq_label_body)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(450, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.wq_label_Author = QtGui.QLabel(self.wq_Frame)
        self.wq_label_Author.setStyleSheet(_fromUtf8("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.wq_label_Author.setFrameShape(QtGui.QFrame.NoFrame)
        self.wq_label_Author.setObjectName(_fromUtf8("wq_label_Author"))
        self.horizontalLayout.addWidget(self.wq_label_Author)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.wq_checkBox_Follow = QtGui.QCheckBox(self.wq_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wq_checkBox_Follow.sizePolicy().hasHeightForWidth())
        self.wq_checkBox_Follow.setSizePolicy(sizePolicy)
        self.wq_checkBox_Follow.setStyleSheet(_fromUtf8("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("view_count.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wq_checkBox_Follow.setIcon(icon)
        self.wq_checkBox_Follow.setTristate(False)
        self.wq_checkBox_Follow.setObjectName(_fromUtf8("wq_checkBox_Follow"))
        self.verticalLayout.addWidget(self.wq_checkBox_Follow)
        self.wq_label_votes = QtGui.QLabel(self.wq_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wq_label_votes.sizePolicy().hasHeightForWidth())
        self.wq_label_votes.setSizePolicy(sizePolicy)
        self.wq_label_votes.setStyleSheet(_fromUtf8("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.wq_label_votes.setObjectName(_fromUtf8("wq_label_votes"))
        self.verticalLayout.addWidget(self.wq_label_votes)
        self.wq_label_answers = QtGui.QLabel(self.wq_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wq_label_answers.sizePolicy().hasHeightForWidth())
        self.wq_label_answers.setSizePolicy(sizePolicy)
        self.wq_label_answers.setStyleSheet(_fromUtf8("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.wq_label_answers.setObjectName(_fromUtf8("wq_label_answers"))
        self.verticalLayout.addWidget(self.wq_label_answers)
        self.wq_label_comments = QtGui.QLabel(self.wq_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wq_label_comments.sizePolicy().hasHeightForWidth())
        self.wq_label_comments.setSizePolicy(sizePolicy)
        self.wq_label_comments.setStyleSheet(_fromUtf8("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.wq_label_comments.setObjectName(_fromUtf8("wq_label_comments"))
        self.verticalLayout.addWidget(self.wq_label_comments)
        self.wq_label_views = QtGui.QLabel(self.wq_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wq_label_views.sizePolicy().hasHeightForWidth())
        self.wq_label_views.setSizePolicy(sizePolicy)
        self.wq_label_views.setStyleSheet(_fromUtf8("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.wq_label_views.setObjectName(_fromUtf8("wq_label_views"))
        self.verticalLayout.addWidget(self.wq_label_views)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)

        self.retranslateUi(FORM)
        QtCore.QMetaObject.connectSlotsByName(FORM)

    def retranslateUi(self, FORM):
        FORM.setWindowTitle(_translate("FORM", "Form", None))
        self.wq_label_Site.setText(_translate("FORM", "TextLabel", None))
        self.wq_label_Title.setText(_translate("FORM", "<html><head/><body><p>Question Title...             </p></body></html>", None))
        self.wq_label_Question_State.setText(_translate("FORM", "TextLabel", None))
        self.wq_label_body.setText(_translate("FORM", "Part of Question entity goes here...                                                                                                                            ", None))
        self.wq_label_Author.setText(_translate("FORM", "Question Author", None))
        self.wq_checkBox_Follow.setText(_translate("FORM", "Follow", None))
        self.wq_label_votes.setText(_translate("FORM", "0 votes", None))
        self.wq_label_answers.setText(_translate("FORM", "0 answers", None))
        self.wq_label_comments.setText(_translate("FORM", "0 comments", None))
        self.wq_label_views.setText(_translate("FORM", "0 views", None))

from QLabelCustom import QLabelCustom
